# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import dataprocessor
import ftp_interaction


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedWidth(591)
        Form.setFixedHeight(214)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 531, 188))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_7.addWidget(self.lineEdit_4)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.download_button)
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_8)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Valles Marineris FTP file downloader"))
        self.label.setText(_translate("Form", "FTP address:"))
        self.label_2.setText(_translate("Form", "FTP username: "))
        self.label_3.setText(_translate("Form", "FTP password: "))
        self.label_4.setText(_translate("Form", "Date of download (DD/MM/YY): "))
        self.pushButton.setText(_translate("Form", "Download file!"))
        self.label_5.setText(_translate("Form", "STATUS:"))
    
    def download_button(self):
        self.ftp_address = self.lineEdit.text()
        self.ftp_username = self.lineEdit_2.text()
        self.ftp_password = self.lineEdit_3.text()
        self.download_date = self.lineEdit_4.text()
        print(self.ftp_address, self.ftp_username, self.ftp_password)

        ftp_interaction_variable = ftp_interaction.ftp_file_download(self.ftp_address, self.ftp_username, self.ftp_password, self.download_date)
        print(ftp_interaction_variable)
        if ftp_interaction_variable == 5:
            self.label_6.setText("<html><head/><body><p align=\"center\" style=\"color: red;\">Cannot connect to FTP server.<br/></p></body></html>")
        if ftp_interaction_variable == 4:
            self.label_6.setText("<html><head/><body><p align=\"center\" style=\"color: red;\">The file cannot be downloaded to this location.<br/></p></body></html>")
        if ftp_interaction_variable == 3:
            self.label_6.setText("<html><head/><body><p align=\"center\" style=\"color: red;\">The file could not be downloaded.<br/></p></body></html>")
        if ftp_interaction_variable == 2:
            self.label_6.setText("<html><head/><body><p align=\"center\" style=\"color: red;\">A file with that name cannot be found,<br/></p></body></html>")
        if ftp_interaction_variable == 1:
            self.label_6.setText("<html><head/><body><p align=\"center\" style=\"color: red;\">Authentication error. Please check your user information.<br/></p></body></html>")
        elif not(ftp_interaction_variable):
            dataprocessor.verifier(ftp_interaction_variable)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
